### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by shdudwns** [thebigsmileXD/PocketAI#7]
[14:17:06] [Server thread/CRITICAL]: ErrorException: "Array to string conversion" (EXCEPTION) in "PocketAI-recode/src/xenialdan/PocketAI/Loader" at line 95

**Comment by shdudwns** [comment]
[14:39:20] [Server thread/CRITICAL]: InvalidArgumentException: "Entity behaviour/properties file: entities/cow not found for entity of type Cow" (EXCEPTION) in "PocketAI-recode/src/xenialdan/PocketAI/EntityProperties" at line 36

**Comment by Aericio** [comment]
It's in heavy development, and XenialDan is most likely aware of these issues already. You shouldn't be using the plugin as it is right now either.

**Comment by inxomnyaa** [comment]
Correctly. I worked on it the last days, and fixed alot of stuff, including some cleanup etc.

The first error is fixed because of how components are working now anyways. It changed quite a bit.

The second error is either related so the array is empty, or the pack could not be loaded.

So or so, i am currently writing with Mojang about an issue i stumbled over today, which seems to be a Mojang-caused error in dolphin.json.

And another time: the plugin is not stable, it may corrupt your complete world.

I might upload the changes i have done this night. The version seems quite stable

**Comment by inxomnyaa** [comment]
If you like, you can test the commit https://github.com/thebigsmileXD/PocketAI/commit/d3f1316f8aafbaca78644829499833272b44269b. It seems to be stable enough. Just beware the mass of output.
(Also, the phantom json file has a too new version and will not be loaded.)
